import type { Metadata } from "next";
import { Providers } from "./provider";
import "./globals.css";
import Head from "./head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head />
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
